export const authConst = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
};

export const userConst = {
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_FAIL: "USER_REGISTER_FAIL",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
};
